version: '3.4'

services:
  web:
    image: 'flask_ducker'
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: flask
    env_file:
      - ./.env
    links:
      - db
    ports: 
      - '5000:5000'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      HTTP_PORT: "5000"
      MYSQL_HOST: ${HOST}
  db:
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
    ports: 
       - '3366:3306'
    # expose:
    #   - 3306
    volumes:
        - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
